version: '3'
services:
  pgsql:
    image: postgres:alpine
    restart: unless-stopped
    container_name: postgre_lib
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./storage/volumes/postgres/data:/var/lib/postgresql/data
      - ./storage/initial_sql/initial_db.sql:/docker-entrypoint-initdb.d/create_schemas.sql
    networks:
      -  postgre-network

  redis:
    image: redis:alpine3.17
    restart: unless-stopped
    container_name: redis_lib
    command: redis-server --save 30 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - './storage/volumes/redis/data:/data'
    networks:
      - redis-network

  meili:
    image: getmeili/meilisearch:v1.1.1
    restart: unless-stopped
    container_name: meili_lib
    command: meilisearch --master-key=${MEILI_KEY}
    environment:
      - http_proxy
    volumes:
      - ./storage/volumes/meili/data:/meili_data
    networks:
      - meili-network

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    environment:
        SOKETI_DEBUG: '1'
        SOKETI_METRICS_SERVER_PORT: '9601'
        SOKETI_DB_REDIS_HOST: redis
        SOKETI_DB_REDIS_PORT: 6379
        SOKETI_DB_REDIS_DB: 2
        SOKETI_DB_REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
        - '${SOKETI_PORT:-6001}:6001'
        - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    networks:
        - soketi-network
        - redis-network

  api:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.local
    container_name: backend_lib
    user: ${UID}:${GID}
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MEILI_KEY=${MEILI_KEY}
      - XDG_CONFIG_HOME=${XDG_CONFIG_HOME}

    volumes:
      -  ./:/var/www
      -  ./docker/extend-php.ini:/usr/local/etc/php/conf.d/extend-php.ini
    ports:
      - "8000:80"
    depends_on:
      - pgsql
      - redis
      - meili
      - soketi
    networks:
      - redis-network
      - postgre-network
      - meili-network
      - soketi-network

networks:
  postgre-network:
  redis-network:
  soketi-network:
  meili-network:
    driver: bridge
