name: Build and Push Docker Images

on:
  push:
    branches:
      - dev
  release:
    types: [released]

env:
  DOCKER_REPO: simanuelle/libapp_backend
  DOCKER_USERNAME: simanuelle
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and Push Latest-Dev Image
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: latest-dev
          dockerfile: docker/Dockerfile

      - name: Build and Push Latest and Release Image
        if: github.ref == 'refs/tags/*'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            latest
            ${{ github.event.release.tag_name#v* }}
          dockerfile: docker/Dockerfile